#redis配置
spring:
  redis:
    database: 0
    host: 192.168.100.10
    port: 6379
    #password:
    jedis:
      pool:
        max-active: 8 #最大连接数
        max-wait: 6000 #最大阻塞等待时间
        max-idle: 8 #最大空闲连接
        min-idle: 0 #最小空闲连接
        timeout: 10000